// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivpaegjtijpmcvzufiml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2cGFlZ2p0aWpwbWN2enVmaW1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NDQ1NTIsImV4cCI6MjA3NDEyMDU1Mn0.kVAvlZw0g2cNcW7RD5Ap1-YJoTjEkbpSi54CR9pLPQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
